baseURL = "Marcel-Maack-hugoAbschluss.github.io"
languageCode = "de"
title = "Mein Hugo Abschluss Seite"
theme = "hugo_theme_beg"
[Author]
    name = "Marcel"
    profile = "https://google.com/+XXX"

[Taxononies]
    tag = "tags"
    kurs = "kurse"

[permalinks]
    post = "/:year/:month/:weekdayname/:title"

[[menu.main]]
    identifier = "kurs"
    name = "Kurse"
    url = "/kurse"
    weight = 2

[[menu.main]]
    name = "Tag"
    url = "/tags"
    weight = 3



